# Banco de itens (MK_PUBLICAR) - usado no autocomplete de "Publicar anúncio".
# Campos: nome, nivel, vocacao, tipo_dano, bonus, protecao, dano_medio,
# slots, tier, peso, drop.
# Armas: tipo_dano = elemento, dano_medio = atk. Capacetes/armaduras: tipo_dano = "",
# dano_medio = Arm (Armadura). Total de itens: 370 (armas 54, capacetes 151, armaduras 165).

_MK_ITENS_DB = [
 [
  "Hailstorm Rod",
  "33",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "27.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Moonlight Rod",
  "33",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "21.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Necrotic Rod",
  "33",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "21.00",
  "Ninguém.",
 ],
 [
  "Snakebite Rod",
  "6",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "13",
  "1",
  "",
  "19.00",
  "Baleful Bunny, Black Sphinx Acolyte, Cobra Vizier, Faceless Bane, Golgordan, Latrivan, Lizard Snakecharmer, Minotaur Cult Zealot, Serpent Spawn, Worm Priestess, Young Goanna.",
 ],
 [
  "Springsprout Rod",
  "37",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "27.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Terra Rod",
  "26",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "45",
  "1",
  "",
  "25.00",
  "Acolyte of the Cult, Adult Goanna, Blemished Spawn, Bloated Man-Maggot, Bonelord, Cobra Vizier, Devourer (Criatura), Drume, Elder Forest Fury, Faceless Bane, Flimsy Lost Soul, Fury, Infernal Phantom, Irgix the Flimsy, Jungle Moister, Lizard Snakecharmer, Madareth, Marid, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Underworld Rod",
  "52",
  "Druids",
  "Death",
  "Nenhum",
  "",
  "75",
  "1",
  "",
  "29.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Northwind Rod",
  "63",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "85",
  "1",
  "",
  "29.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Shimmer Rod",
  "65",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "85",
  "2",
  "",
  "31.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon.",
 ],
 [
  "Glacial Rod",
  "65",
  "Druids",
  "Ice",
  "Magic Level +1",
  "",
  "85",
  "2",
  "",
  "37.00",
  "Droga: Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon, Ice Dragon, Ice Dragon.",
 ],
 [
  "Muck Rod",
  "65",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "85",
  "2",
  "",
  "37.00",
  "Droga: Carnisylvan, ... Durante Invasões: Oodok Witchmaster.",
 ],
 [
  "The Chiller",
  "0",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "6",
  "0",
  "",
  "15.00",
  "Ninguém.",
 ],
 [
  "Ogre Scepta",
  "37",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "29.00",
  "Ogre Sage, Ogre Shaman, Shaper Matriarch.",
 ],
 [
  "Rod of Destruction",
  "33",
  "Druids",
  "Death",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "27.00",
  "Ninguém.",
 ],
 [
  "Sorcerer and Druid Staff",
  "0",
  "",
  "Energy",
  "Nenhum",
  "",
  "25",
  "0",
  "",
  "19.00",
  "Ninguém.",
 ],
 [
  "The Scorcher",
  "0",
  "Sorcerers",
  "Fire",
  "Nenhum",
  "",
  "4",
  "0",
  "",
  "15.00",
  "Ninguém.",
 ],
 [
  "Wand of Vortex",
  "6",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "13",
  "1",
  "",
  "19.00",
  "Novice of the Cult.",
 ],
 [
  "Wand of Dragonbreath",
  "13",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "19",
  "1",
  "",
  "23.00",
  "Cinder Wyrmling, Crazed Summer Vanguard, Dark Apprentice, Fire Devil, Inkwing, Insane Siren, Manticore, Menacing Carnivor, Herald of Fire.",
 ],
 [
  "Wand of Decay",
  "19",
  "Sorcerer",
  "Death",
  "Nenhum",
  "",
  "30",
  "1",
  "",
  "23.00",
  "Candy Horror, Dark Apprentice, Knowledge Elemental, Menacing Carnivor, Merlkin, Ogre Shaman, Orc Cult Priest, Orc Shaman, Priestess Of The Wild Sun, Shaper Matriarch, Venerable Girtablilu.",
 ],
 [
  "Wand of Draconia",
  "22",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "30",
  "1",
  "",
  "27.00",
  "Blistering Fire Elemental, Crazed Summer Vanguard, Elder Wyrm, Feral Sphinx, Gazer Spectre, Insane Siren, Magma Crawler, Manticore, Ogre Rowdy, Seacrest Serpent, Wyrm.",
 ],
 [
  "Wand of Cosmic Energy",
  "26",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "45",
  "1",
  "",
  "25.00",
  "Amenef The Burning, Arachnophobica, Blemished Spawn, Burster Spectre, Clavius, Diamond Servant, Diamond Servant Replica, Elf Arcanist, Energy Elemental, Flimsy Lost Soul, Gorzindel, High Voltage Elemental, Irgix the Flimsy, Knowledge Elemental, Mercurial Menace, Minotaur Mage, Quara Hydromancer, Quara Hydromancer Scout, Raubritter Chastener, Realityquake, Renegade Quara Hydromancer, Souleater, Sparkion, Spectre, Thanatursus, Tremendous Tyrant, Twisted Shaper, Usurper Warlock, Venerable Girtablilu, Yielothax.",
 ],
 [
  "Wand of Inferno",
  "33",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "27.00",
  "Amenef The Burning, Arbaziloth, Dawnfire Asura, Dragon, Draken Spellweaver, Efreet, Eldritch Dragon Lord, Enlightened of the Cult, Essence Of Malice, Feral Sphinx, Gazer Spectre, Gravedigger, Guardian Of Tales, Hand of Cursed Fate, Hellfire Fighter, Hellhound, Insane Siren, Lava Golem, Lizard Dragon Priest, Lokathmor, Madareth, Massive Fire Elemental, Ogre Rowdy, Shaburak Demon, Shaburak Lord, Shaburak Prince, The Baron from Below, The Count Of The Core, The Duke Of The Depths, Thornfire Wolf, True Dawnfire Asura, Vulcongra, Wrathful Archivist, Wyvern.",
 ],
 [
  "Wand of Dimensions",
  "37",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "55",
  "4",
  "",
  "28.00",
  "Mazzinor.",
 ],
 [
  "Wand of Starstorm",
  "37",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "25.50",
  "Amenef The Burning, Blemished Spawn, Clavius, Converter, Dark Carnisylvan, Elder Wyrm, Energuardian Of Tales, Flimsy Lost Soul, Headpecker, Infernal Phantom, Irgix the Flimsy, Lloyd, Madareth, Massive Energy Elemental, Mazzinor, Menacing Carnivor, Overcharged Energy Elemental, Poisonous Carnisylvan, Raubritter Chastener, Retching Horror, Shulgrax, Sphinx, Tremendous Tyrant, Usurper Warlock, Varnished Diremaw, Werehyaena Shaman, Wyrm.",
 ],
 [
  "Shimmer Wand",
  "40",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "65",
  "0",
  "",
  "31.00",
  "Ninguém.",
 ],
 [
  "Wand of Darkness",
  "41",
  "Sorcerers",
  "Death",
  "Magic Level +2",
  "",
  "85",
  "0",
  "",
  "32.00",
  "Ninguém.",
 ],
 [
  "Wand of Voodoo",
  "42",
  "Sorcerer",
  "Death",
  "Nenhum",
  "",
  "65",
  "1",
  "",
  "28.50",
  "Black Sphinx Acolyte, Burster Spectre, Carnivostrich, Draken Abomination, Drume, Flimsy Lost Soul, Ghulosh, Grimeleech, Infernal Phantom, Madareth, Menacing Carnivor, Shaper Matriarch, Sharpclaw, Usurper Commander, Undertaker, Venerable Girtablilu, Werebadger, Werehyaena Shaman. Durante Invasões: Feroxa (Mortal).",
 ],
 [
  "Ferumbras' Staff (Wand)",
  "65",
  "Sorcerers",
  "Energy",
  "Nenhum",
  "",
  "95",
  "0",
  "",
  "22.50",
  "Ninguém.",
 ],
 [
  "Wand of Defiance",
  "65",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "85",
  "2",
  "",
  "37.00",
  "Bulltaur Forgepriest, Cliff Strider, Essence Of Malice, Harpy, Lady Tenebris, Mercurial Menace, Norcferatu Nightweaver, Orewalker, Seacrest Serpent, Sphinx, Thanatursus, The Souldespoiler, Venerable Girtablilu. Durante Invasões: Mawhawk.",
 ],
 [
  "Wand of Everblazing",
  "65",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "85",
  "2",
  "",
  "37.00",
  "Adventurer Group, Essence Of Malice, Lava Golem, Magma Crawler, Manticore, Mazoran, Ogre Rowdy, Priestess Of The Wild Sun, Rage Squid, The Source Of Corruption, Weeper, Gaffir. Durante Invasões: Furyosa.",
 ],
 [
  "Dream Blossom Staff",
  "80",
  "Sorcerers and Druids",
  "Energy",
  "Nenhum",
  "",
  "70",
  "2",
  "",
  "32.00",
  "Boogy, Dark Faun, Mercurial Menace, Nymph, Pixie, Pooka, Sugar Mommy.",
 ],
 [
  "Ferumbras' Staff (Enchanted Wand)",
  "100",
  "Sorcerers",
  "Energy",
  "Nenhum",
  "",
  "110",
  "0",
  "",
  "34.00",
  "Ninguém.",
 ],
 [
  "Jungle Wand",
  "150",
  "Sorcerers",
  "Earth",
  "Magic Level +1",
  "Ice +3%",
  "80-100",
  "4",
  "",
  "32.00",
  "Ratmiral Blackwhiskers",
 ],
 [
  "Deepling Ceremonial Dagger",
  "180",
  "Sorcerers and Druids",
  "Ice",
  "Magic Level +1",
  "Earth +5%",
  "90",
  "3",
  "",
  "32.00",
  "Brokul",
 ],
 [
  "Energized Limb",
  "180",
  "Sorcerers and Druids",
  "Fire",
  "Magic Level +1",
  "Energy +10%",
  "98",
  "3",
  "",
  "27.00",
  "Maxxenius.",
 ],
 [
  "Wand of Destruction",
  "200",
  "Sorcerers",
  "Energy",
  "Nenhum",
  "",
  "88",
  "2",
  "",
  "35.00",
  "Ninguém.",
 ],
 [
  "Lion Wand",
  "220",
  "Sorcerers",
  "Ice",
  "Magic Level +2",
  "",
  "89-109",
  "4",
  "",
  "21.00",
  "Ancient Lion Knight, Drume.",
 ],
 [
  "Deepling Fork",
  "230",
  "Sorcerers and Druids",
  "Ice",
  "Magic Level +2",
  "Holy +8%",
  "90",
  "3",
  "",
  "33.00",
  "Brokul.",
 ],
 [
  "Eldritch Wand",
  "250",
  "Sorcerers",
  "Fire",
  "Magic Level +2, Fire Magic Level +1",
  "Energy +4%",
  "85-105",
  "4",
  "",
  "36.00",
  "The Brainstealer.",
 ],
 [
  "Gilded Eldritch Wand",
  "250",
  "Sorcerers",
  "Fire",
  "Magic Level +2, Fire Magic Level +1",
  "Energy +4%",
  "85-105",
  "4",
  "",
  "37.00",
  "The Brainstealer.",
 ],
 [
  "Naga Wand",
  "250",
  "Sorcerers",
  "Energy",
  "Magic Level +2, Energy Magic Level +1",
  "Ice +4%",
  "90-120",
  "4",
  "",
  "28.00",
  "Timira the Many-Headed",
 ],
 [
  "Cobra Wand",
  "270",
  "Sorcerers",
  "Energy",
  "Magic Level +2",
  "",
  "95",
  "4",
  "",
  "19.00",
  "Scarlett Etzel, Gaffir.",
 ],
 [
  "Draining Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "4",
  "",
  "24.00",
  "Ninguém.",
 ],
 [
  "Falcon Wand",
  "300",
  "Sorcerer",
  "Energy",
  "Magic Level +3",
  "Fire +8%",
  "100",
  "4",
  "",
  "33.00",
  "Grand Canon Dominus, Grand Master Oberon.",
 ],
 [
  "Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "4",
  "",
  "24.00",
  "Arbaziloth.",
 ],
 [
  "Rending Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "4",
  "",
  "24.00",
  "Ninguém.",
 ],
 [
  "Siphoning Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "4",
  "",
  "24.00",
  "Ninguém.",
 ],
 [
  "Amber Wand",
  "330",
  "Sorcerers",
  "Energy",
  "Magic Level +2, Energy Magic Level +2",
  "Ice +6%",
  "",
  "4",
  "",
  "20.00",
  "The Rootkraken.",
 ],
 [
  "Soultainter",
  "400",
  "Sorcerers",
  "Death",
  "Magic Level +4",
  "Death +12%",
  "100-120",
  "4",
  "",
  "19.00",
  "Ninguém.",
 ],
 [
  "Crypt Bile",
  "450",
  "Sorcerers",
  "Physical",
  "Magic Level +4",
  "Fire +6%",
  "",
  "4",
  "",
  "20.00",
  "Ninguém.",
 ],
 [
  "Grand Sanguine Coil",
  "600",
  "Sorcerers",
  "Fire",
  "Magic Level +4, Fire Magic Level +1, Energy Magic Level +1",
  "Earth +7%",
  "114",
  "4",
  "",
  "21.00",
  "Bakragore dentro de uma Bag You Covet.",
 ],
 [
  "Sanguine Coil",
  "600",
  "Sorcerers",
  "Fire",
  "Magic Level +4, Fire Magic Level +1, Energy Magic Level +1",
  "Earth +7%",
  "114",
  "4",
  "",
  "22.00",
  "Bakragore, Chagorz, Ichgahal, Murcion e Vemiath, dentro de uma Bag You Covet.",
 ],
 [
  "Moonsilver Channeler",
  "1000",
  "Sorcerers",
  "",
  "Magic Level +6, Death Magic Level +1",
  "Energy +7%",
  "",
  "4",
  "",
  "23.50",
  "Phosphorus.",
 ],
 [
  "Stellar Moonsilver Channeler",
  "1000",
  "Sorcerers",
  "",
  "Magic Level +6, Death Magic Level +1",
  "Energy +7%",
  "",
  "4",
  "",
  "24.80",
  "Ninguém.",
 ],
 [
  "Amazon Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "2",
  "4",
  "29.50",
  "Durante Invasões:\nOrc Warlord.",
 ],
 [
  "Ancient Tiara",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "4",
  "24.00",
  "Durante Eventos:\nElf Arcanist,\nRescelus.",
 ],
 [
  "Bandana",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "2.00",
  "Durante Eventos:\nAmazon,\nGozzan Elite,\nSainted Amazon.",
 ],
 [
  "Blue Spectacles",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "3",
  "2.50",
  "Ninguém.",
 ],
 [
  "Bonelord Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "3",
  "5.00",
  "Ninguém.",
 ],
 [
  "Brass Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "1",
  "63.00",
  "Ninguém.",
 ],
 [
  "Bridal Wreath",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "2",
  "3.00",
  "Ninguém.",
 ],
 [
  "Broken Iks Headpiece",
  "120",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "1",
  "4",
  "30.00",
  "Ninguém.",
 ],
 [
  "Broken Visor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "2",
  "7.00",
  "Ninguém.",
 ],
 [
  "Ceremonial Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "1",
  "3",
  "12.00",
  "Durante Eventos:\nWitch,\nWitch Knight.",
 ],
 [
  "Chain Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "1",
  "30.00",
  "Ninguém.",
 ],
 [
  "Charmer's Tiara",
  "100",
  "Todas",
  "",
  "Shielding +4",
  "",
  "8",
  "2",
  "4",
  "9.00",
  "Lady Bufon,\nMorax the Magnificent,\nSirhide,\nThe Charmer.",
 ],
 [
  "Charred Mask",
  "175",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "2",
  "4",
  "25.00",
  "The Charmer.",
 ],
 [
  "Cobra Crown",
  "120",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "2",
  "4",
  "35.00",
  "Scarlett Etzel.",
 ],
 [
  "Crown",
  "0",
  "Nenhuma",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "1",
  "25.00",
  "Ninguém.",
 ],
 [
  "Crown Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "1",
  "15.00",
  "Durante Eventos:\nGolden Knight,\nGygnus the Undefeated.",
 ],
 [
  "Crusader Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "1",
  "36.00",
  "Ninguém.",
 ],
 [
  "Damaged Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "2",
  "10.50",
  "Ninguém.",
 ],
 [
  "Dark Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "0",
  "1",
  "26.50",
  "Ninguém.",
 ],
 [
  "Demon Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "13",
  "0",
  "3",
  "41.00",
  "Durante Invasões:\nDemon,\nDemon Master,\nAnkrahm,\nAngry Demon,\nFerumbras Mortal Shell,\nHeralds of the Air,\nManiacal Demon,\nManiacal Demon Killer,\nMercyless Flame,\nRift Demon,\nRozelie the Pale,\nSilencer.",
 ],
 [
  "Devil Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "1",
  "1",
  "44.00",
  "Blazing Fire Elemental,\nOtherworldly Entity,\nQuara Predator,\nSearing Fire Elemental,\nServant Golem,\nSpark of Destruction,\nThe Many,\nVolatile Fire Elemental.",
 ],
 [
  "Dragon Scale Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "3",
  "20.50",
  "Durante Eventos:\nDragon,\nGreater Dragon.",
 ],
 [
  "Dwarven Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "1",
  "1",
  "38.00",
  "Durante Invasões:\nDwarf Elder,\nDwarf Guard,\nDwarf Henchman,\nDwarf King,\nDwarf Soldier,\nDwarf Worker,\nFrost Giant,\nFrost Giantess,\nKreebosh the Exile,\nMarx the Undefeated,\nSkullhunter,\nSnow Gnome,\nWar Golem (Durante Invasões),\nYeti.",
 ],
 [
  "Feather Headdress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "2",
  "7.00",
  "Ninguém.",
 ],
 [
  "Ferumbras' Candy Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "2",
  "8.50",
  "Durante Eventos:\nFerumbras Mortal Shell.",
 ],
 [
  "Ferumbras' Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "2",
  "27.00",
  "Ninguém.",
 ],
 [
  "Flower Wreath",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "1.50",
  "Ninguém.",
 ],
 [
  "Full Helmet of the Ancients",
  "60",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "0",
  "2",
  "28.00",
  "Ninguém.",
 ],
 [
  "Fur Cap",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "1",
  "19.00",
  "Durante Eventos:\nBear,\nHuntress.",
 ],
 [
  "Glacier Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "2",
  "3.00",
  "Ninguém.",
 ],
 [
  "Golden Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "3",
  "13.00",
  "Ninguém.",
 ],
 [
  "Golden Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "2",
  "3",
  "36.00",
  "Ninguém.",
 ],
 [
  "Golden Horned Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "2",
  "31.00",
  "Ninguém.",
 ],
 [
  "Green Demon Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "14",
  "0",
  "3",
  "41.00",
  "Ninguém.",
 ],
 [
  "Gryphon Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "24.00",
  "Durante Eventos:\nKing Tibianus,\nPillar of Death (Durante Eventos),\nRukel the Destroyer.",
 ],
 [
  "Hat of the Mad",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "1",
  "3.00",
  "Durante Invasões:\nBanshee,\nDark Apprentice,\nDark Magician,\nDemon,\nDemon Master,\nGrim Reaper,\nLethal Lissy,\nNeutral Demon,\nNightmare,\nPhantasm,\nWraith.",
 ],
 [
  "Helmet of Nature",
  "50",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "2",
  "3",
  "15.00",
  "Ninguém.",
 ],
 [
  "Helmet of the Ancients",
  "20",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "2",
  "10.00",
  "Durante Eventos:\nMadareth.",
 ],
 [
  "Helmet of the Deep",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "3",
  "22.00",
  "Durante Invasões:\nDragon,\nGreater Dragon,\nWyrm (Durante Eventos).",
 ],
 [
  "Helmet of The Lost",
  "60",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "0",
  "3",
  "23.00",
  "Durante Eventos:\nThe Lost.",
 ],
 [
  "Helmet of Ultimate Terror",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "0",
  "2",
  "45.00",
  "Ninguém.",
 ],
 [
  "Horned Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "0",
  "1",
  "32.00",
  "Ninguém.",
 ],
 [
  "Horseman Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "1",
  "43.00",
  "Ninguém.",
 ],
 [
  "Incandescent Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "2",
  "25.00",
  "Ninguém.",
 ],
 [
  "Iron Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "1",
  "21.00",
  "Ninguém.",
 ],
 [
  "Iron Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "1",
  "40.00",
  "Ninguém.",
 ],
 [
  "Ivory Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "21.00",
  "Ninguém.",
 ],
 [
  "Jester Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "3",
  "4.00",
  "Ninguém.",
 ],
 [
  "Krimhorn Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "31.00",
  "Durante Eventos:\nSoul Maiden,\nSoul Rider.",
 ],
 [
  "Laurel Wreath",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "1.00",
  "Ninguém.",
 ],
 [
  "Leaf Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "6.00",
  "Ninguém.",
 ],
 [
  "Leather Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "1",
  "11.00",
  "Ninguém.",
 ],
 [
  "Legion Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "1",
  "35.00",
  "Ninguém.",
 ],
 [
  "Light Bandana",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "0.50",
  "Ninguém.",
 ],
 [
  "Lightning Headband",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "0",
  "2",
  "3.00",
  "Ninguém.",
 ],
 [
  "Mage Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "1",
  "6.00",
  "Ninguém.",
 ],
 [
  "Mage's Cap",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "0",
  "1",
  "13.00",
  "Ninguém.",
 ],
 [
  "Magician Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "2",
  "7.00",
  "Ninguém.",
 ],
 [
  "Magma Monocle",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "3",
  "2.00",
  "Ninguém.",
 ],
 [
  "Mighty Helm of Green Sparks",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "0",
  "3",
  "35.00",
  "Ninguém.",
 ],
 [
  "Mining Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "2",
  "18.00",
  "Ninguém.",
 ],
 [
  "Mining Helmet (Budrik)",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "3",
  "2",
  "18.00",
  "Budrik Ditob.",
 ],
 [
  "Mirror Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "17.00",
  "Ninguém.",
 ],
 [
  "Mystic Turban",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "8.00",
  "Ninguém.",
 ],
 [
  "Odd Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "1",
  "8.00",
  "Ninguém.",
 ],
 [
  "Pair of Earmuffs",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "0.10",
  "Ninguém.",
 ],
 [
  "Party Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "7.00",
  "Durante Eventos:\nSun-Touched Boar.",
 ],
 [
  "Pirate Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "1",
  "22.00",
  "Durante Invasões:\nPirate Buccaneer,\nPirate Cutthroat,\nPirate Ghost,\nPirate Marauder,\nPirate Sculptor.",
 ],
 [
  "Porcelain Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "5.00",
  "Ninguém.",
 ],
 [
  "Post Officer's Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "2",
  "9.00",
  "Ninguém.",
 ],
 [
  "Ragnir Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "38.00",
  "Durante Eventos:\nRagnir.",
 ],
 [
  "Reflecting Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "2",
  "18.00",
  "Ninguém.",
 ],
 [
  "Royal Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "3",
  "26.00",
  "Ninguém.",
 ],
 [
  "Rusty Winged Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "0",
  "1",
  "30.00",
  "Ninguém.",
 ],
 [
  "Santa Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "3",
  "5.00",
  "Durante Eventos:\nA Crazed Reindeer,\nSanta Claus.",
 ],
 [
  "Sedge Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "1",
  "13.00",
  "Ninguém.",
 ],
 [
  "Sensing Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "20.00",
  "Ninguém.",
 ],
 [
  "Shamanic Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "7.00",
  "Ninguém.",
 ],
 [
  "Silver Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "2",
  "9.00",
  "Ninguém.",
 ],
 [
  "Skull Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "2",
  "24.00",
  "Durante Invasões:\nCrypt Warden,\nDemon Hunter,\nScarlet Siren.",
 ],
 [
  "Soldier Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "1",
  "28.00",
  "Ninguém.",
 ],
 [
  "Sphinx Tiara",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "2",
  "12.00",
  "Ninguém.",
 ],
 [
  "Spooky Hood",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "0",
  "2",
  "30.00",
  "Ninguém.",
 ],
 [
  "Steel Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "49.00",
  "Ninguém.",
 ],
 [
  "Strange Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "3",
  "7.00",
  "Ninguém.",
 ],
 [
  "Studded Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "1",
  "30.00",
  "Ninguém.",
 ],
 [
  "Terra Hood",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "2",
  "25.00",
  "Ninguém.",
 ],
 [
  "The Crown of the Percht Queen (Fire)",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Fire +10%",
  "10",
  "0",
  "3",
  "35.00",
  "Durante Eventos:\nPercht Queen.",
 ],
 [
  "The Crown of the Percht Queen (Ice)",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Ice +10%",
  "10",
  "0",
  "3",
  "35.00",
  "Durante Eventos:\nPercht Queen.",
 ],
 [
  "The Epic Wisdom",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "4",
  "30.00",
  "Durante Eventos:\nGrandmother.",
 ],
 [
  "Traditional Gamsbart Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "10.00",
  "Ninguém.",
 ],
 [
  "Tribal Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "3.00",
  "Durante Invasões:\nAmazon,\nGozzan Elite,\nSainted Amazon.",
 ],
 [
  "Viking Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "1",
  "38.00",
  "Ninguém.",
 ],
 [
  "Visage of the End Days",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "0",
  "2",
  "46.00",
  "Ninguém.",
 ],
 [
  "Warrior Helmet",
  "0",
  "Nenhuma",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "1",
  "36.00",
  "Ninguém.",
 ],
 [
  "Winged Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "25.00",
  "Ninguém.",
 ],
 [
  "Witch Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "1",
  "3",
  "5.00",
  "Durante Invasões:\nWitch,\nWitch Knight.",
 ],
 [
  "Wood Cape",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "1",
  "25.00",
  "Ninguém.",
 ],
 [
  "Zaoan Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "1",
  "2",
  "27.00",
  "Ninguém.",
 ],
 [
  "Batwing Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "0",
  "2",
  "8.00",
  "Durante Eventos:\nBat.",
 ],
 [
  "Jade Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "1",
  "3",
  "8.00",
  "Ninguém.",
 ],
 [
  "Coned Hat of Enlightenment",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "2",
  "12.00",
  "Ninguém.",
 ],
 [
  "Rubber Cap",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "1",
  "2",
  "1.00",
  "Ninguém.",
 ],
 [
  "Crest of the Deep Seas",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "3",
  "7.00",
  "Ninguém.",
 ],
 [
  "Yalahari Mask",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "2",
  "26.00",
  "Ninguém.",
 ],
 [
  "Elite Draken Helmet",
  "180",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "2",
  "4",
  "37.00",
  "Brutus.",
 ],
 [
  "Enchanted Werewolf Helmet (Axe)",
  "100",
  "Todas",
  "",
  "",
  "Physical +4%",
  "9",
  "0",
  "4",
  "64.00",
  "Ninguém.",
 ],
 [
  "Enchanted Werewolf Helmet (Club)",
  "100",
  "Todas",
  "",
  "",
  "Physical +4%",
  "9",
  "0",
  "4",
  "64.00",
  "Ninguém.",
 ],
 [
  "Enchanted Werewolf Helmet (Distance)",
  "100",
  "Todas",
  "",
  "",
  "Physical +4%",
  "9",
  "0",
  "4",
  "64.00",
  "Ninguém.",
 ],
 [
  "Enchanted Werewolf Helmet (Fist)",
  "100",
  "Todas",
  "",
  "",
  "Physical +4%",
  "9",
  "0",
  "4",
  "64.00",
  "Ninguém.",
 ],
 [
  "Enchanted Werewolf Helmet (Magic)",
  "100",
  "Todas",
  "",
  "",
  "Physical +4%",
  "9",
  "0",
  "4",
  "64.00",
  "Ninguém.",
 ],
 [
  "Enchanted Werewolf Helmet (Sword)",
  "100",
  "Todas",
  "",
  "",
  "Physical +4%",
  "9",
  "0",
  "4",
  "64.00",
  "Ninguém.",
 ],
 [
  "Tiara of Power",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "3",
  "11.00",
  "Ninguém.",
 ],
 [
  "Werewolf Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "0",
  "3",
  "38.00",
  "Ninguém.",
 ],
 [
  "Jade Conical Hat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "2",
  "9.00",
  "Ninguém.",
 ],
 [
  "Depth Galea",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "3",
  "10.00",
  "Ninguém.",
 ],
 [
  "Gill Gugel",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "1",
  "2",
  "4.00",
  "Ninguém.",
 ],
 [
  "Prismatic Helmet",
  "175",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "1",
  "3",
  "24.00",
  "Durante Eventos:\nCinder Beast,\nFaerwood Sentinel,\nFear Beast.",
 ],
 [
  "Shroud of Despair",
  "100",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "0",
  "4",
  "15.00",
  "Ninguém.",
 ],
 [
  "Dark Vision Bandana",
  "200",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "1",
  "4",
  "5.00",
  "Ninguém.",
 ],
 [
  "Dark Whispers",
  "200",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "1",
  "4",
  "45.00",
  "Drume.",
 ],
 [
  "Gnome Helmet",
  "100",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "1",
  "4",
  "24.00",
  "Durante Eventos:\nFloating Island Boss,\nMegasylvan Yselda,\nMr. Punch and Judy,\nShulgrax,\nSpriteling.",
 ],
 [
  "Galea Mortis",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "3",
  "19.00",
  "Durante Invasões:\nHerald of Gloom.",
 ],
 [
  "Lion Spangenhelm",
  "200",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "1",
  "4",
  "42.00",
  "Lion Knight.",
 ],
 [
  "Norcferatu Bonehood",
  "200",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "1",
  "4",
  "45.00",
  "norcferatu Nightstriker.",
 ],
 [
  "Terra Helmet",
  "180",
  "Druids and Sorcerers",
  "",
  "Magic Level +2",
  "Life Drain +8%",
  "10",
  "2",
  "4",
  "18.00",
  "Timira the Many-Headed.",
 ],
 [
  "Antler-Horn Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "0",
  "2",
  "26.00",
  "Ninguém.",
 ],
 [
  "Eldritch Cowl",
  "250",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "1",
  "4",
  "14.00",
  "The Brainstealer.",
 ],
 [
  "Eldritch Hood",
  "250",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "1",
  "4",
  "14.00",
  "The Brainstealer.",
 ],
 [
  "Stoic Iks Casque",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "1",
  "2",
  "8.00",
  "Ninguém.",
 ],
 [
  "Stoic Iks Headpiece",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "1",
  "3",
  "12.00",
  "Ninguém.",
 ],
 [
  "Cobra Hood",
  "270",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "1",
  "4",
  "33.00",
  "Scarlett Etzel.",
 ],
 [
  "Norcferatu Skullguard",
  "200",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "0",
  "4",
  "44.00",
  "Ninguém.",
 ],
 [
  "Demon Mengu",
  "250",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "1",
  "4",
  "23.00",
  "Shulgrax.",
 ],
 [
  "Demonfang Mask",
  "250",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "0",
  "4",
  "30.00",
  "Shulgrax.",
 ],
 [
  "Dreadfire Headpiece",
  "250",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "1",
  "4",
  "28.00",
  "Ninguém.",
 ],
 [
  "Falcon Circlet",
  "300",
  "Knights",
  "",
  "Distance Fighting +2",
  "",
  "11",
  "1",
  "4",
  "30.00",
  "Baron Moss,\nGrand Canon Dominus,\nOsmar.",
 ],
 [
  "Falcon Coif",
  "300",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "1",
  "4",
  "30.00",
  "Baron Moss,\nGrand Canon Dominus,\nOsmar.",
 ],
 [
  "Hellstalker Visor",
  "350",
  "Knights",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "1",
  "4",
  "20.00",
  "Ninguém.",
 ],
 [
  "Maliceforged Helmet",
  "400",
  "Knights",
  "",
  "Nenhum",
  "Fire +6%",
  "13",
  "1",
  "4",
  "55.00",
  "Ninguém.",
 ],
 [
  "Stag Helmet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "2",
  "18.00",
  "Durante Eventos:\nStag.",
 ],
 [
  "Alicorn Headguard",
  "1000",
  "Knights",
  "",
  "Dist Skill +4",
  "",
  "14",
  "1",
  "0",
  "25.00",
  "Drume.",
 ],
 [
  "Arboreal Crown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "0",
  "2",
  "28.00",
  "Durante Eventos:\nFaerwood Sentinel.",
 ],
 [
  "Arcanomancer Regalia",
  "500",
  "Mages",
  "",
  "Magic Level +4",
  "",
  "13",
  "2",
  "4",
  "24.00",
  "Drume.",
 ],
 [
  "Ethereal Coned Hat",
  "150",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "1",
  "4",
  "5.00",
  "Ninguém.",
 ],
 [
  "Spiritthorn Helmet",
  "400",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "0",
  "4",
  "20.00",
  "Drume.",
 ],
 [
  "Moonsilver Battle Visor",
  "1000",
  "Knights",
  "",
  "",
  "",
  "14",
  "1",
  "0",
  "23.00",
  "Ninguém.",
 ],
 [
  "Moonsilver Nimbus Hat",
  "1000",
  "Knights",
  "",
  "",
  "",
  "14",
  "1",
  "0",
  "23.00",
  "Ninguém.",
 ],
 [
  "Moonsilver Spirit Mask",
  "1000",
  "Knights",
  "",
  "",
  "",
  "14",
  "1",
  "0",
  "23.00",
  "Ninguém.",
 ],
 [
  "Moonsilver Strike Helm",
  "1000",
  "Knights",
  "",
  "",
  "",
  "14",
  "1",
  "0",
  "23.00",
  "Ninguém.",
 ],
 [
  "Moonsilver Trail Hood",
  "1000",
  "Knights",
  "",
  "",
  "",
  "14",
  "1",
  "0",
  "23.00",
  "Ninguém.",
 ],
 [
  "Albino Plate",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "2",
  "3",
  "84.00",
  "White Pale.",
 ],
 [
  "Ball Gown",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "25.00",
  "Ninguém",
 ],
 [
  "Belted Cape",
  "0",
  "Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "0",
  "1",
  "35.00",
  "Afflicted Strider, Amenef The Burning, Bog Raider, Crazed Summer Vanguard, Gladiator, Undead Elite Gladiator, Undead Gladiator.\nDurante Invasões:\nWeakened Shlorg.",
 ],
 [
  "Blue Robe",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "2",
  "2",
  "22.00",
  "Banshee, Enlightened of the Cult, Feversleep, Girtablilu Warrior, Hellgorak, Horadron, Lich, Lokathmor, Lumbering Carnivor, Midnight Asura, Quara Mantassin, Renegade Quara Mantassin, Spiky Carnivor, Tamru the Black, Terrorsleep, True Midnight Asura, Vashresamun, Warlock.\nDurante Invasões:\nCountess Sorrow, Grandfather Tridian, Gravelord Oshuran, The Handmaiden, Zarabustor.",
 ],
 [
  "Brass Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "8",
  "0",
  "1",
  "80.00",
  "Bandit, Crypt Defiler, Gladiator, Grave Robber, Hunter, Minotaur Archer, Minotaur Guard, Nomad, Nomad (Blue), Orc Warlord, Quara Constrictor, Quara Constrictor Scout, Renegade Quara Constrictor, The Horned Fox, Undead Gladiator, Wild Warrior.\nDurante Invasões:\nGeneral Murius.",
 ],
 [
  "Broken Iks Cuirass",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "0",
  "19.00",
  "Ahau, Iks Aucar.",
 ],
 [
  "Buckle",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "0",
  "2",
  "75.00",
  "Lost Basher, Lost Exile, Lost Husher, Lost Thrower, Spiky Carnivor.",
 ],
 [
  "Burial Shroud",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Death +5%",
  "0",
  "0",
  "0",
  "5.00",
  "Ninguém",
 ],
 [
  "Cape",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "1",
  "32.00",
  "Ekatrix, Ghost, Lizard Snakecharmer, Quara Mantassin, Renegade Quara Mantassin, Tarnished Spirit, Two-Headed Turtle, Witch, Lizard Magician.\nDurante Invasões:\nYaga the Crone.",
 ],
 [
  "Chain Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "2",
  "1",
  "100.00",
  "Barbarian Bloodwalker, Barbarian Brutetamer, Blood Crab, Deepsea Blood Crab, Dwarf Soldier, Juvenile Cyclops, Lizard Sentinel, Minotaur, Minotaur Bruiser, Minotaur Guard, Minotaur Poacher, Orc Berserker, Orc Shaman, Orc Warrior, Pirate Marauder, Quara Mantassin Scout, Scar Tribe Warrior, Valkyrie.",
 ],
 [
  "Coat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "1",
  "27.00",
  "Ekatrix, Frost Troll, Witch.\nDurante Invasões:\nYaga the Crone.",
 ],
 [
  "Crown Armor",
  "0",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "13",
  "1",
  "2",
  "99.00",
  "Ashmunrah, Cliff Strider, Demon Outcast, Execowtioner, Gorzindel, Hand of Cursed Fate, Hellgorak, Hero, Horadron, King Zelos, Orewalker, Phantasm, Prince Drazzak, Quara Pincher, Raubritter Skirmisher, Renegade Knight, Renegade Quara Pincher, Serpent Spawn, The Noxious Spawn, Thul, Vile Grandmaster.",
 ],
 [
  "Dark Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "0",
  "1",
  "120.00",
  "Adlerauge, Ancient Lion Knight, Behemoth, Bibby Bloodbath, Black Knight, Blight Mariner, Bretzecutioner, Clavius, Destroyer, Gargoyle, Ghastly Dragon, Michael the Stalwart, Overseer Osverger, Pirate Corsair, Spiky Carnivor, Werelion.\nDurante Invasões:\nArthom the Hunter, Dracola.\nDurante Eventos:\nHaunted Dragon.",
 ],
 [
  "Demon Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "16",
  "2",
  "2",
  "80.00",
  "Ninguém",
 ],
 [
  "Doublet",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "0",
  "1",
  "25.00",
  "Afflicted Strider, Amenef The Burning, Dawnfly, Gore Horn, Gorerilla, Hulking Prehemoth, Jungle Moa, Spiky Carnivor, Werehyaena Shaman, Werelion.",
 ],
 [
  "Dragon Scale Mail",
  "0",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "15",
  "1",
  "2",
  "114.00",
  "Demodras, Dragon Lord, Frost Dragon, Paiz the Pauperizer, Soul of Dragonking Zyrtarch, Albino Dragon.\nDurante Invasões:\nChizzoron the Distorter.\nDurante Eventos:\nGelidrazah the Frozen, Ice Dragon, Kalyassa, Tazhadur.",
 ],
 [
  "Dwarven Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Physical +5%",
  "10",
  "2",
  "3",
  "130.00",
  "Ninguém",
 ],
 [
  "Elven Mail",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "3",
  "3",
  "90.00",
  "Ravenous Hunger.",
 ],
 [
  "Ethno Coat",
  "0",
  "Sorcerers and Druids",
  "",
  "Magic Level +1",
  "Nenhuma",
  "7",
  "0",
  "1",
  "25.50",
  "Ninguém.",
 ],
 [
  "Flower Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "19.00",
  "Dryad.",
 ],
 [
  "Focus Cape",
  "0",
  "Sorcerers and Druids",
  "",
  "Magic Level +1",
  "Nenhuma",
  "9",
  "0",
  "2",
  "21.00",
  "Afflicted Strider, Amenef The Burning, Converter, Dawnfire Asura, Draken Spellweaver, Girtablilu Warrior, Harpy, Hellgorak, Lizard Dragon Priest, Lumbering Carnivor, Nightmare Scion, Pirat Cutthroat, Raging Mage, Reality Reaver, Sea Serpent, Tremendous Tyrant, True Dawnfire Asura, Wyrm.\nDurante Invasões:\nCaptain Jones.",
 ],
 [
  "Girl's Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "13.00",
  "Ninguém",
 ],
 [
  "Golden Armor",
  "0",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "14",
  "2",
  "2",
  "80.00",
  "Falcon Knight, Falcon Paladin, Ferumbras Mortal Shell, Golden Servant, Golden Servant Replica, Grand Canon Dominus, Grand Commander Soeren, Hellflayer, Hellgorak, Horadron, Horestis, Juggernaut, Katex Blood Tongue, Kerberos, Phosphorus, Preceptor Lazare, The Last Lore Keeper, Undead Dragon, Warlock, Zanakeph.\nDurante Invasões:\nFerumbras, Ghazbaran, Massacre.",
 ],
 [
  "Goo Shell",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Earth +2%, Fire -2%",
  "12",
  "0",
  "3",
  "58.00",
  "Durante Invasões:\nWeakened Shlorg.",
 ],
 [
  "Green Demon Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "16",
  "2",
  "4",
  "80.00",
  "Ninguém.\nDurante Invasões:\nMorshabaal",
 ],
 [
  "Green Tunic",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "1",
  "9.30",
  "Elf Arcanist, Hero, Vicious Squire.\nDurante Invasões:\nFernfang.",
 ],
 [
  "Heat Core",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "2",
  "2",
  "55.00",
  "Glooth Brigand, Glooth Fairy, Glooth Golem.",
 ],
 [
  "Heavy Metal T-Shirt",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "2",
  "2",
  "8.00",
  "Boogey.",
 ],
 [
  "Hibiscus Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "19.00",
  "Angry Sugar Fairy, Boreth, Nymph, Vampire Bride, Wyrm.",
 ],
 [
  "Jacket",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "1",
  "24.00",
  "Ninguém.",
 ],
 [
  "Knight Armor",
  "0",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "2",
  "2",
  "120.00",
  "Afflicted Strider, Amenef The Burning, Black Knight, Brutus Bloodbeard, Crystal Spider, Deadeye Devious, Esmeralda, Falcon Knight, Fleshcrawler, Giant Spider, Grand Chaplain Gaunder, Hand of Cursed Fate, Hydra, Juggernaut, Lethal Lissy, Medusa, Mooh'Tah Warrior, Naga Warrior, Pirat Cutthroat, Preceptor Lazare, Quara Hydromancer, Quara Hydromancer Scout, Rhindeer, Ron The Ripper, Sir Leonard, Sir Leopold, Stampor, Terrorsleep, The Bloodweb, The Many, The Old Widow, The Snapper, Tromphonyte, Undead Dragon, Usurper Archer, Zanakeph.\nDurante Invasões:\nMamma Longlegs, The Welter.",
 ],
 [
  "Leather Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "4",
  "0",
  "1",
  "60.00",
  "Dworc Fleshhunter, Dworc Venomsniper, Dworc Voodoomaster, Goblin, Goblin Assassin, Goblin Leader, Goblin Scavenger, Mountain Troll, Muglex Clan Assassin, Muglex Clan Footman, Muglex Clan Scavenger.\nDurante Invasões:\nOodok Witchmaster.",
 ],
 [
  "Leather Harness",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "0",
  "1",
  "29.00",
  "Corym Charlatan, Corym Skirmisher, Corym Vanguard.",
 ],
 [
  "Leopard Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "2",
  "2",
  "95.00",
  "Assassin.",
 ],
 [
  "Magic Plate Armor",
  "0",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "17",
  "2",
  "2",
  "85.00",
  "Angry Demon, Arbaziloth, Demon, Dracola, Ferumbras Mortal Shell, Grimeleech, Harpy, Hellflayer, Katex Blood Tongue, Rage Squid, Rotrender, Shulgrax, Terofar, The Source Of Corruption, Utua Stone Sting, Vexclaw, Yirkas Blue Scales.\nDurante Invasões:\nFerumbras, Ghazbaran, Morgaroth, Orshabaal, Sight of Surrender.\nDurante Eventos:\nBones.",
 ],
 [
  "Magician's Robe",
  "0",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Nenhuma",
  "6",
  "0",
  "1",
  "25.00",
  "The Corruptor, Corrupted Skeleton",
 ],
 [
  "Mammoth Fur Cape",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "2",
  "2",
  "20.00",
  "Barbaria, Barbarian Brutetamer, Ravenous Hunger, The Bloodtusk.",
 ],
 [
  "Monk Robe",
  "0",
  "Monks",
  "",
  "Fist Fighting +1",
  "Nenhuma",
  "7",
  "0",
  "1",
  "70.00",
  "Tarantula.",
 ],
 [
  "Mooh'tah Plate",
  "0",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "12",
  "2",
  "2",
  "125.00",
  "Minotaur Hunter, Minotaur Invader, Mooh'Tah Warrior, Bullwark.",
 ],
 [
  "Native Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "0",
  "4",
  "80.00",
  "Ninguém",
 ],
 [
  "Noble Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "11",
  "2",
  "1",
  "120.00",
  "Ninguém",
 ],
 [
  "Old Cape",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "3",
  "35.00",
  "Ninguém",
 ],
 [
  "Pair of Old Bracers",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "0",
  "2.00",
  "Thaian.",
 ],
 [
  "Paladin Armor",
  "0",
  "Paladins",
  "",
  "Distance Fighting +2",
  "Nenhuma",
  "12",
  "1",
  "2",
  "65.00",
  "Annihilon, Bog Raider, Terofar, Zavarash.\nDurante Invasões:\nZulazza the Corruptor.",
 ],
 [
  "Pirate Shirt",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "3",
  "0",
  "1",
  "20.00",
  "Pirate Buccaneer, Pirate Gunner.",
 ],
 [
  "Plain Monk Robe",
  "0",
  "Monks",
  "",
  "Fist Fighting +1",
  "Nenhuma",
  "6",
  "0",
  "1",
  "65.00",
  "Desconhecido.",
 ],
 [
  "Plate Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "10",
  "0",
  "1",
  "120.00",
  "Ancient Lion Knight, Ancient Scarab, Behemoth, Black Knight, Bonebeast, Brutus Bloodbeard, Crystal Spider, Cursed Ape, Deadeye Devious, Destroyer, Dreadbeast, Giant Spider, High Templar Cobrass, Kongra, Lethal Lissy, Lizard Templar, Naga Warrior, Orc Cult Fanatic, Orc Leader, Orc Warlord, Pirate Buccaneer, Quara Pincher Scout, Ron The Ripper, Sacred Spider, The Snapper, Undead Elite Gladiator, Undead Gladiator, Valkyrie.\nDurante Invasões:\nWarlord Ruzad.",
 ],
 [
  "Ranger's Cloak",
  "0",
  "Paladins",
  "",
  "Nenhum",
  "Nenhuma",
  "7",
  "0",
  "1",
  "48.00",
  "Corrupted Skeleton, The Corruptor, Corrupted Ghost, Muglex Clan Footman e Muglex Clan Assassin.",
 ],
 [
  "Red Robe",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "1",
  "26.00",
  "Adept of the Cult, Banshee, Pirate Ghost.\nDurante Invasões:\nCaptain Jones.",
 ],
 [
  "Red Tunic",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "2",
  "0",
  "0",
  "14.00",
  "Ninguém",
 ],
 [
  "Scale Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "9",
  "0",
  "1",
  "105.00",
  "Barbarian Headsplitter, Barbarian Skullhunter, Dwarf Guard, Ghoul, Lizard Sentinel, Minotaur Archer, Mutated Human, Orc Rider, Pirate Cutthroat, Quara Predator Scout, Undead Prospector, Lizard Commander.\nDurante Invasões:\nGrorlam.",
 ],
 [
  "Simple Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "10.00",
  "Banshee, Zombie.",
 ],
 [
  "Spectral Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "",
  "0",
  "0",
  "10.00",
  "Ninguém",
 ],
 [
  "Spirit Cloak",
  "0",
  "Sorcerers and Druids",
  "",
  "Magic Level +1",
  "Nenhuma",
  "8",
  "0",
  "1",
  "26.50",
  "Afflicted Strider, Goggle Cake, Hellgorak, Nightstalker, Renegade Quara Hydromancer, Sea Serpent, Werelion.",
 ],
 [
  "Studded Armor",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "5",
  "0",
  "1",
  "71.00",
  "Brittle Skeleton, Crazed Dwarf, Dwarf, Dwarf Miner, Elf, Minotaur Bruiser, Minotaur Poacher, Orc, Scar Tribe Shaman, Troll Marauder, Woodling.",
 ],
 [
  "Summer Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Death +5%",
  "0",
  "0",
  "0",
  "10.00",
  "Swan Maiden.",
 ],
 [
  "The Rain Coat",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "1",
  "0",
  "0",
  "32.00",
  "Mephiles.",
 ],
 [
  "Traditional Shirt",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "4.00",
  "Ninguém.",
 ],
 [
  "Tunic",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "15.00",
  "Ninguém",
 ],
 [
  "White Dress",
  "0",
  "Todas",
  "",
  "Nenhum",
  "Nenhuma",
  "0",
  "0",
  "0",
  "24.00",
  "Ninguém",
 ],
 [
  "Glooth Cape",
  "40",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Earth +5%, Fire -5%",
  "9",
  "0",
  "2",
  "29.00",
  "Devourer (Criatura), Glooth Anemone, Glooth Bandit, Glooth Fairy, Lisa, Tremor Worm.",
 ],
 [
  "Fur Armor",
  "50",
  "Todas",
  "",
  "Nenhum",
  "Earth +5%, Ice +5%",
  "11",
  "0",
  "2",
  "49.00",
  "Adult Goanna, Blemished Spawn, Bloodback, Cave Chimera, Girtablilu Warrior, Lumbering Carnivor, Michael the Stalwart, Shadowpelt, Raubritter Skirmisher, Rotten Golem, Turbulent Elemental, Varnished Diremaw, Werebear, Wereboar, Werepanther, Young Goanna.\nDurante Invasões:\nFeroxa (Mortal), Owin (Criatura).",
 ],
 [
  "Glacier Robe",
  "50",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Ice +8%, Energy -8%",
  "11",
  "0",
  "2",
  "22.50",
  "Crazed Winter Rearguard, Crazed Winter Vanguard, Girtablilu Warrior, Goggle Cake, Icecold Book, King Zelos, Quara Pincher, Quara Predator, Squid Warden, Srezz Yellow Eyes, Tarbaz, Tremendous Tyrant, Turbulent Elemental.\nDurante Invasões:\nZushuka (Mortal), Yakchal.\nDurante Eventos:\nSchiach.",
 ],
 [
  "Lightning Robe",
  "50",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Energy +8%, Earth -8%",
  "11",
  "0",
  "2",
  "22.50",
  "Anomaly, Bulltaur Forgepriest, Court Warlock, Cursed Prospector, Elder Wyrm, High Voltage Elemental, Mad Mage, Prince Drazzak, Raubritter Chastener, Realityquake, Tyrn, Warlock.\nDurante Invasões:\nOmrafir, Zarabustor.",
 ],
 [
  "Magma Coat",
  "50",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Fire +8%, Ice -8%",
  "11",
  "0",
  "2",
  "22.50",
  "Afflicted Strider, Burning Book, Cinder Wyrmling, Crape Man, Dawnfire Asura, Diabolic Imp, Fire Overlord, Gazer Spectre, Girtablilu Warrior, Gorerilla, Guardian Of Tales, Hellfire Fighter, Hellhound, Insane Siren, King Zelos, Lava Golem, Manticore, Mazoran, Scarlett Etzel, Shaburak Lord, Shaburak Prince, Stalking Stalk, The Baron from Below, The Flaming Orchid, The Sandking, True Dawnfire Asura, Urmahlullu the Weakened, Vulcongra, Wandering Pillar, Weeper.\nDurante Invasões:\nFuryosa, Gaz'Haragoth, Morgaroth, The Imperor.\nDurante Eventos:\nPercht.",
 ],
 [
  "Terra Mantle",
  "50",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Earth +8%, Fire -8%",
  "11",
  "0",
  "2",
  "22.50",
  "Adlerauge, Ancient Spawn of Morgathla, Askarak Lord, Askarak Prince, Banshee, Blightwalker, Bramble Wyrmling, Choking Fear, Cursed Book, Drume, Earth Overlord, Esmeralda, Exotic Cave Spider, Feral Werecrocodile, Fleshcrawler, Glooth Bandit, Glooth Brigand, Gorgo, Hideous Fungus, Humongous Fungus, Ink Blob, Ink Splash, Medusa, Raubritter Marksman, Rotten Golem, Scarlett Etzel, Spiky Carnivor.\nDurante Invasões:\nThe Evil Eye.",
 ],
 [
  "Witchhunter's Coat",
  "50",
  "Todas",
  "",
  "Nenhum",
  "Death +2%, Holy -2%",
  "11",
  "0",
  "0",
  "25.00",
  "Ninguém",
 ],
 [
  "Zaoan Armor",
  "50",
  "Knights and Paladins",
  "",
  "Speed +10",
  "Nenhuma",
  "13",
  "0",
  "2",
  "95.50",
  "Darklight Emitter, Draken Abomination, Draken Elite, Draken Warmaster, Ethershreck, Fazzrah, Ghastly Dragon, Lizard Chosen, Lizard High Guard, Lizard Legionnaire, Lizard Zaogun, Paiz the Pauperizer.\nDurante Invasões:\nBattlemaster Zunzu.",
 ],
 [
  "Zaoan Monk Robe",
  "50",
  "Monks",
  "",
  "Fist Fighting +1",
  "Nenhuma",
  "7",
  "0",
  "2",
  "110.00",
  "Ethershreck, Hatebreeder, Soul of Dragonking Zyrtarch, Lizard Templar.",
 ],
 [
  "Amazon Armor",
  "60",
  "Paladins",
  "",
  "Distance Fighting +3",
  "Nenhuma",
  "13",
  "2",
  "4",
  "45.00",
  "Durante Invasões:\nOrc Warlord.",
 ],
 [
  "Crystalline Armor",
  "60",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Ice +3%, Energy -3%",
  "13",
  "0",
  "2",
  "84.50",
  "Animated Feather, Armadile, Blight Mariner, Crystal Wolf, Darklight Source, Diamond Servant, Diamond Servant Replica, Eradicator, Haunted Hunter, Icecold Book, Ice Overlord, Mazzinor, Melting Frozen Horror, Michael the Stalwart, Orewalker, Prince Drazzak, Realityquake, Ravenous Hunger, Roaming Dread, Sea Serpent, Squid Warden, The Count Of The Core, Tunnel Tyrant, Turbulent Elemental.\nDurante Invasões:\nGhazbaran.",
 ],
 [
  "Lavos Armor",
  "60",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Fire +3%, Ice -3%",
  "13",
  "0",
  "2",
  "85.00",
  "Annihilon, Fire Overlord, Terofar, Zavarash",
 ],
 [
  "Spellweaver's Robe",
  "60",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Energy +10%, Earth -10%",
  "11",
  "0",
  "2",
  "23.50",
  "Arbaziloth, Bulltaur Alchemist, Burning Gladiator, Draken Spellweaver, Ethershreck, Ghastly Dragon, Hatebreeder, Juvenile Bashmu, Lady Tenebris, Lloyd, Lokathmor, The Duke Of The Depths, Undead Dragon, Utua Stone Sting, Wrathful Archivist, Yirkas Blue Scales.\nDurante Eventos:\nHaunted Dragon.",
 ],
 [
  "Swamplair Armor",
  "60",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Earth +3%, Fire -3%",
  "13",
  "0",
  "2",
  "84.50",
  "Cursed Book, Earth Overlord, Feral Werecrocodile, Ink Blob, Paiz the Pauperizer, Serpent Spawn, The Enraged Thorn Knight, The Noxious Spawn.\nDurante Invasões:\nChizzoron the Distorter.",
 ],
 [
  "Swan Feather Cloak",
  "60",
  "Todas",
  "",
  "Speed +10",
  "Earth +12%, Energy +12%",
  "12",
  "0",
  "2",
  "4.00",
  "Ninguém.",
 ],
 [
  "Voltage Armor",
  "60",
  "Knights and Paladins",
  "",
  "Nenhum",
  "Energy +3%, Earth -3%",
  "13",
  "0",
  "2",
  "84.50",
  "Energy Overlord, Hellgorak, Terofar, The Last Lore Keeper.",
 ],
 [
  "Zaoan Robe",
  "60",
  "Sorcerers and Druids",
  "",
  "Nenhum",
  "Fire +10%, Ice -10%",
  "11",
  "0",
  "2",
  "24.50",
  "Lizard Dragon Priest, Draken Spellweaver.\nDurante Invasões:\nFlamecaller Zazrak.",
 ],
 [
  "Dark Lord's Cape",
  "65",
  "Sorcerers",
  "",
  "Nenhum",
  "Death +8%, Holy -8%",
  "11",
  "0",
  "4",
  "29.00",
  "Durante Invasões:\nMorgaroth.",
 ],
 [
  "Divine Plate",
  "75",
  "Paladins",
  "",
  "Nenhum",
  "Death +10%, Holy -10%",
  "13",
  "0",
  "2",
  "75.00",
  "Dragon Pack, Ferumbras Mortal Shell, Undead Dragon, Zanakeph.\nDurante Invasões:\nFerumbras.",
 ],
 [
  "Dragon Robe",
  "75",
  "Sorcerers",
  "",
  "Nenhum",
  "Fire +12%, Ice -12%",
  "12",
  "0",
  "2",
  "28.50",
  "Durante Invasões:\nFuryosa, Morgaroth.",
 ],
 [
  "Frozen Plate",
  "75",
  "Paladins",
  "",
  "Nenhum",
  "Ice +7%, Energy -7%",
  "13",
  "0",
  "2",
  "75.00",
  "Leviathan, Melting Frozen Horror, Renegade Quara Predator.\nDurante Invasões:\nGhazbaran.\nDurante Eventos:\nGelidrazah the Frozen.",
 ],
 [
  "Ghazbaran Oyoroi",
  "75",
  "Monks",
  "",
  "Fist Fighting +1, Magic Level +1",
  "Energy +7%, Ice -7%",
  "8",
  "0",
  "4",
  "135.00",
  "Ghazbaran.",
 ],
 [
  "Greenwood Coat",
  "75",
  "Druids",
  "",
  "Nenhum",
  "Earth +12%, Fire -12%",
  "12",
  "0",
  "2",
  "28.50",
  "Ferumbras Mortal Shell.\nDurante Invasões:\nFerumbras, Chizzoron the Distorter.",
 ],
 [
  "Molten Plate",
  "75",
  "Paladins",
  "",
  "Nenhum",
  "Fire +7%, Ice -7%",
  "13",
  "0",
  "4",
  "75.00",
  "Durante Invasões:\nMorgaroth.",
 ],
 [
  "Robe of the Ice Queen",
  "75",
  "Druids",
  "",
  "Nenhum",
  "Ice +12%, Energy -12%",
  "12",
  "0",
  "4",
  "29.50",
  "Durante Invasões:\nGhazbaran.",
 ],
 [
  "Spirit Bind",
  "75",
  "Monks",
  "",
  "Fist Fighting +2",
  "Energy +5%, Ice -5%",
  "8",
  "0",
  "2",
  "135.00",
  "Ninguém.",
 ],
 [
  "Velvet Mantle",
  "75",
  "Sorcerers",
  "",
  "Nenhum",
  "Energy +12%, Earth -12%",
  "12",
  "0",
  "2",
  "28.50",
  "Ferumbras Mortal Shell, The False God.\nDurante Invasões:\nFerumbras.",
 ],
 [
  "Calopteryx Cape",
  "80",
  "Sorcerers and Druids",
  "",
  "Magic Level +1",
  "Ice +5%",
  "12",
  "0",
  "2",
  "20.00",
  "Hive Overseer, Kollos, Spidris, Spidris Elite, Spitter, The Sandking, The Baron from Below.",
 ],
 [
  "Yalahari Armor",
  "80",
  "Knights",
  "",
  "Nenhum",
  "Death +3%",
  "16",
  "0",
  "2",
  "70.00",
  "Ninguém.",
 ],
 [
  "Skullcracker Armor",
  "85",
  "Knights",
  "",
  "Nenhum",
  "Death +5%, Holy -5%",
  "14",
  "0",
  "2",
  "110.00",
  "Annihilon, Bony Sea Devil, Frost Flower Asura, Grim Reaper, Midnight Asura, Sopping Corpus, The Moonlight Aster, The Scourge of Oblivion, The Source Of Corruption, True Frost Flower Asura, True Midnight Asura, Undead Dragon.\nDurante Eventos:\nHaunted Dragon.",
 ],
 [
  "Earthborn Titan Armor",
  "100",
  "Knights",
  "",
  "Axe Fighting +2",
  "Earth +5%, Fire -5%",
  "15",
  "0",
  "4",
  "120.00",
  "Ancient Spawn of Morgathla, Lord of the Elements, Terofar.\nDurante Invasões:\nZulazza the Corruptor.",
 ],
 [
  "Elite Draken Mail",
  "100",
  "Knights and Paladins",
  "",
  "Speed +10",
  "Nenhuma",
  "15",
  "2",
  "2",
  "120.00",
  "Draken Elite, Paiz the Pauperizer.",
 ],
 [
  "Fireborn Giant Armor",
  "100",
  "Knights",
  "",
  "Sword Fighting +2",
  "Fire +5%, Ice -5%",
  "15",
  "0",
  "2",
  "120.00",
  "Ancient Spawn of Morgathla, Lord of the Elements.\nDurante Invasões:\nMorgaroth.",
 ],
 [
  "Master Archer's Armor",
  "100",
  "Paladins",
  "",
  "Distance Fighting +3",
  "Nenhuma",
  "15",
  "1",
  "3",
  "69.00",
  "Ninguém.",
 ],
 [
  "Merudri Scale Mail",
  "100",
  "Monks",
  "",
  "Fist Fighting +2",
  "Fire +4%",
  "7",
  "0",
  "3",
  "29.00",
  "Ninguém.",
 ],
 [
  "Oceanborn Leviathan Armor",
  "100",
  "Knights",
  "",
  "Shielding +1",
  "Ice +5%, Energy -5%",
  "15",
  "0",
  "4",
  "100.00",
  "Lord of the Elements.\nDurante Invasões:\nGhazbaran.",
 ],
 [
  "Robe of the Underworld",
  "100",
  "Sorcerers",
  "",
  "Nenhum",
  "Death +12%, Holy -12%",
  "12",
  "0",
  "2",
  "31.00",
  "Ancient Spawn of Morgathla.\nDurante Invasões:\nOrshabaal.",
 ],
 [
  "Royal Draken Mail",
  "100",
  "Knights",
  "",
  "Shielding +3",
  "Physical +5%",
  "16",
  "0",
  "3",
  "130.00",
  "Ninguém.",
 ],
 [
  "Royal Scale Robe",
  "100",
  "Sorcerers and Druids",
  "",
  "Magic Level +2",
  "Fire +5%",
  "12",
  "0",
  "3",
  "45.00",
  "Ninguém.",
 ],
 [
  "Windborn Colossus Armor",
  "100",
  "Knights",
  "",
  "Club Fighting +2",
  "Energy +5%, Earth -5%",
  "15",
  "0",
  "2",
  "120.00",
  "Ninguém",
 ],
 [
  "Prismatic Armor",
  "120",
  "Knights and Paladins",
  "",
  "Speed +15",
  "Physical +5%",
  "15",
  "1",
  "2",
  "79.00",
  "Ninguém.",
 ],
 [
  "Merudri Nanbando",
  "125",
  "Monks",
  "",
  "Fist Fighting +3",
  "Nenhuma",
  "7",
  "1",
  "2",
  "106.00",
  "Ninguém.",
 ],
 [
  "Furious Frock",
  "130",
  "Sorcerers and Druids",
  "",
  "Magic Level +2",
  "Fire +5%",
  "12",
  "0",
  "4",
  "34.00",
  "Durante Invasões:\nFuryosa.",
 ],
 [
  "Depth Lorica",
  "150",
  "Paladins",
  "",
  "Distance Fighting +3",
  "Death +5%",
  "16",
  "2",
  "2",
  "145.00",
  "Jaul.",
 ],
 [
  "Gill Coat",
  "150",
  "Sorcerers and Druids",
  "",
  "Magic Level +1",
  "Earth +10%, Fire -10%",
  "12",
  "0",
  "2",
  "19.00",
  "Ninguém.",
 ],
 [
  "Gnomish Cuirass",
  "150",
  "Monks",
  "",
  "Fist Fighting +3",
  "Physical +2%",
  "8",
  "1",
  "2",
  "100.00",
  "Ninguém.",
 ],
 [
  "Robe of Enlightenment",
  "150",
  "Monks",
  "",
  "Fist Fighting +3",
  "Ice +4%",
  "8",
  "1",
  "1",
  "24.00",
  "Ninguém.",
 ],
 [
  "Dream Shroud",
  "180",
  "Sorcerers and Druids",
  "",
  "Magic Level +3",
  "Energy +10%",
  "12",
  "1",
  "3",
  "25.00",
  "Alptramun.",
 ],
 [
  "Living Armor",
  "180",
  "Sorcerers and Druids",
  "",
  "Magic Level +2",
  "Earth +12%, Fire -5%",
  "13",
  "1",
  "3",
  "48.00",
  "Plagueroot.",
 ],
 [
  "Earthheart Cuirass",
  "200",
  "Knights",
  "",
  "Sword Fighting +4",
  "Earth +8%, Fire -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Earthheart Hauberk",
  "200",
  "Knights",
  "",
  "Axe Fighting +4",
  "Earth +8%, Fire -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Earthheart Platemail",
  "200",
  "Knights",
  "",
  "Club Fighting +4",
  "Earth +8%, Fire -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Earthmind Raiment",
  "200",
  "Sorcerers and Druids",
  "",
  "Magic Level +4",
  "Earth +8%, Fire -8%",
  "15",
  "0",
  "2",
  "55.00",
  "Ninguém.",
 ],
 [
  "Earthsoul Tabard",
  "200",
  "Paladins",
  "",
  "Distance Fighting +4",
  "Earth +8%, Fire -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Energy Robe",
  "200",
  "Monks",
  "",
  "Fist Fighting +4",
  "Energy +8%, Earth -8%",
  "9",
  "0",
  "2",
  "75.00",
  "Ninguém.",
 ],
 [
  "Fireheart Cuirass",
  "200",
  "Knights",
  "",
  "Sword Fighting +4",
  "Fire +8%, Ice -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Fireheart Hauberk",
  "200",
  "Knights",
  "",
  "Axe Fighting +4",
  "Fire +8%, Ice -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Fireheart Platemail",
  "200",
  "Knights",
  "",
  "Club Fighting +4",
  "Fire +8%, Ice -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Firemind Raiment",
  "200",
  "Sorcerers and Druids",
  "",
  "Magic Level +4",
  "Fire +8%, Ice -8%",
  "15",
  "0",
  "2",
  "55.00",
  "Ninguém.",
 ],
 [
  "Firesoul Tabard",
  "200",
  "Paladins",
  "",
  "Distance Fighting +4",
  "Fire +8%, Ice -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Frostheart Cuirass",
  "200",
  "Knights",
  "",
  "Sword Fighting +4",
  "Ice +8%, Energy -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Frostheart Hauberk",
  "200",
  "Knights",
  "",
  "Axe Fighting +4",
  "Ice +8%, Energy -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Frostheart Platemail",
  "200",
  "Knights",
  "",
  "Club Fighting +4",
  "Ice +8%, Energy -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Frostmind Raiment",
  "200",
  "Sorcerers and Druids",
  "",
  "Magic Level +4",
  "Ice +8%, Energy -8%",
  "15",
  "0",
  "2",
  "55.00",
  "Ninguém.",
 ],
 [
  "Frostsoul Tabard",
  "200",
  "Paladins",
  "",
  "Distance Fighting +4",
  "Ice +8%, Energy -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Gnome Armor",
  "200",
  "Paladins",
  "",
  "Distance Fighting +3",
  "Physical +4%, Energy +8%, Ice -2%",
  "17",
  "2",
  "3",
  "120.00",
  "The Baron from Below.",
 ],
 [
  "Ice Robe",
  "200",
  "Monks",
  "",
  "Fist Fighting +4",
  "Ice +8%, Energy -8%",
  "9",
  "0",
  "2",
  "75.00",
  "Ninguém.",
 ],
 [
  "Leaf Robe",
  "200",
  "Monks",
  "",
  "Fist Fighting +4",
  "Earth +8%, Fire -8%",
  "9",
  "0",
  "2",
  "75.00",
  "Ninguém",
 ],
 [
  "Magma Robe",
  "200",
  "Monks",
  "",
  "Fist Fighting +4",
  "Fire +8%, Ice -8%",
  "9",
  "0",
  "2",
  "75.00",
  "Ninguém.",
 ],
 [
  "Ornate Chestplate",
  "200",
  "Knights",
  "",
  "Shielding +3",
  "Physical +8%",
  "16",
  "2",
  "2",
  "156.00",
  "Jaul.",
 ],
 [
  "Thunderheart Cuirass",
  "200",
  "Knights",
  "",
  "Sword Fighting +4",
  "Energy +8%, Earth -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Thunderheart Hauberk",
  "200",
  "Knights",
  "",
  "Axe Fighting +4",
  "Energy +8%, Earth -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Thunderheart Platemail",
  "200",
  "Knights",
  "",
  "Club Fighting +4",
  "Energy +8%, Earth -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Thundermind Raiment",
  "200",
  "Sorcerers and Druids",
  "",
  "Magic Level +4",
  "Energy +8%, Earth -8%",
  "15",
  "0",
  "2",
  "55.00",
  "Ninguém.",
 ],
 [
  "Thundersoul Tabard",
  "200",
  "Paladins",
  "",
  "Distance Fighting +4",
  "Energy +8%, Earth -8%",
  "18",
  "0",
  "2",
  "145.00",
  "Ninguém",
 ],
 [
  "Embrace of Nature",
  "220",
  "Paladins",
  "",
  "Distance Fighting +4",
  "Ice +11%, Energy -3%",
  "16",
  "1",
  "3",
  "24.00",
  "Count Vlarkorth, Duke Krule, Lord Azaram, Sir Baeloc.",
 ],
 [
  "Toga Mortis",
  "220",
  "Sorcerers",
  "",
  "Magic Level +4",
  "Death +6%",
  "16",
  "1",
  "3",
  "52.00",
  "King Zelos.",
 ],
 [
  "Bear Skin",
  "230",
  "Druids",
  "",
  "Magic Level +4",
  "Earth +11%, Fire -2%",
  "16",
  "1",
  "3",
  "44.00",
  "Lord Azaram, Duke Krule, Count Vlarkorth, Sir Baeloc.",
 ],
 [
  "Death Oyoroi",
  "230",
  "Monks",
  "",
  "Fist Fighting +4, Magic Level +1",
  "Death +5%",
  "9",
  "1",
  "3",
  "105.00",
  "Sir Nictros, King Zelos.",
 ],
 [
  "Ghost Chestplate",
  "230",
  "Paladins",
  "",
  "Distance Fighting +2",
  "Physical +3%",
  "17",
  "2",
  "3",
  "123.00",
  "The Fear Feaster, The Pale Worm.",
 ],
 [
  "Eldritch Cuirass",
  "250",
  "Knights",
  "",
  "Nenhum",
  "Physical +10%",
  "16",
  "2",
  "4",
  "110.00",
  "The Brainstealer.",
 ],
 [
  "Stoic Iks Chestplate",
  "250",
  "Knights",
  "",
  "Shielding +3",
  "Physical +8%",
  "16",
  "2",
  "4",
  "142.00",
  "Mitmah Vanguard.",
 ],
 [
  "Stoic Iks Cuirass",
  "250",
  "Druids",
  "",
  "Magic Level +4",
  "Death +5%",
  "15",
  "1",
  "4",
  "44.00",
  "Mitmah Vanguard.",
 ],
 [
  "Stoic Iks Robe",
  "250",
  "Monks",
  "",
  "Fist Fighting +4",
  "Physical +2%, Energy +5%",
  "9",
  "2",
  "4",
  "128.00",
  "Mitmah Vanguard.",
 ],
 [
  "Dawnfire Sherwani",
  "270",
  "Sorcerers",
  "",
  "Magic Level +4",
  "Fire +10%, Earth -2%",
  "16",
  "1",
  "4",
  "28.00",
  "Timira the Many-Headed",
 ],
 [
  "Lion Plate",
  "270",
  "Knights",
  "",
  "Sword Fighting +3, Club Fighting +3, Axe Fighting +3",
  "Physical +6%",
  "17",
  "2",
  "4",
  "150.00",
  "Ancient Lion Knight, Drume.",
 ],
 [
  "Mutated Skin Armor",
  "270",
  "Paladins",
  "",
  "Distance Fighting +3",
  "Physical +3%, Earth +8%",
  "17",
  "2",
  "4",
  "63.00",
  "The Monster.",
 ],
 [
  "Naga Tanko",
  "270",
  "Monks",
  "",
  "Fist Fighting +3, Magic Level +2",
  "Physical +2%, Fire +6%",
  "10",
  "2",
  "4",
  "90.00",
  "Timira the Many-Headed",
 ],
 [
  "Norcferatu Bloodhide",
  "270",
  "Sorcerers",
  "",
  "Energy Magic Level +6, Fire Magic Level +3",
  "Earth +8%",
  "16",
  "1",
  "4",
  "39.00",
  "Vladrukh.",
 ],
 [
  "Norcferatu Bonecloak",
  "270",
  "Druids",
  "",
  "Earth Magic Level +6, Healing Magic Level +3",
  "Ice +8%",
  "16",
  "1",
  "4",
  "42.00",
  "Vladrukh.",
 ],
 [
  "Norcferatu Tuskplate",
  "270",
  "Knights",
  "",
  "Sword Fighting +3, Club Fighting +3, Axe Fighting +3",
  "Physical +4%",
  "22",
  "0",
  "4",
  "148.00",
  "Vladrukh",
 ],
 [
  "Arcane Dragon Robe",
  "300",
  "Sorcerers",
  "",
  "Magic Level +3, Energy Magic Level +1",
  "Ice +12%, Fire -6%",
  "15",
  "1",
  "4",
  "43.00",
  "Dragon Hoard.",
 ],
 [
  "Dauntless Dragon Scale Armor",
  "300",
  "Knights",
  "",
  "Sword Fighting +3, Club Fighting +3, Axe Fighting +3",
  "Physical +8%",
  "18",
  "2",
  "4",
  "152.00",
  "Dragon Hoard.",
 ],
 [
  "Falcon Plate",
  "300",
  "Knights",
  "",
  "Shielding +4",
  "Physical +12%",
  "18",
  "2",
  "4",
  "188.00",
  "Grand Canon Dominus, Grand Master Oberon.",
 ],
 [
  "Merudri Battle Mail",
  "300",
  "Monks",
  "",
  "Fist Fighting +4, Magic Level +1",
  "Earth +10%, Energy -5%",
  "10",
  "2",
  "4",
  "29.00",
  "Dragon Pack",
 ],
 [
  "Midnight Tunic",
  "300",
  "Druids",
  "",
  "Magic Level +4",
  "Physical +3%",
  "16",
  "1",
  "4",
  "27.00",
  "Timira the Many-Headed.",
 ],
 [
  "Mystical Dragon Robe",
  "300",
  "Druids",
  "",
  "Magic Level +3, Earth Magic Level +1",
  "Fire +12%, Ice -6%",
  "15",
  "1",
  "4",
  "38.00",
  "Dragon Hoard.",
 ],
 [
  "Unerring Dragon Scale Armor",
  "300",
  "Paladins",
  "",
  "Distance Fighting +3, Holy Magic Level +1",
  "Energy +10%, Earth -5%",
  "17",
  "2",
  "4",
  "135.00",
  "Dragon Hoard.",
 ],
 [
  "Stag Plate",
  "350",
  "Paladins",
  "",
  "Distance Fighting +3, Shielding +3",
  "Physical +3%, Ice +8%",
  "17",
  "2",
  "4",
  "130.00",
  "Court Warlock.",
 ],
 [
  "Stag Robe",
  "350",
  "Monks",
  "",
  "Fist Fighting +4",
  "Physical +4%",
  "10",
  "2",
  "4",
  "80.00",
  "Court Warlock.",
 ],
 [
  "Soulgarb",
  "400",
  "Monks",
  "",
  "Fist Fighting +4 , Magic Level +2",
  "Physical +4%, Ice +8%",
  "11",
  "2",
  "4",
  "107.00",
  "Ninguém.",
 ],
 [
  "Soulmantle",
  "400",
  "Sorcerers",
  "",
  "Magic Level +4",
  "Physical +4%",
  "17",
  "2",
  "4",
  "24.00",
  "Ninguém.",
 ],
 [
  "Soulshell",
  "400",
  "Paladins",
  "",
  "Distance Fighting +4",
  "Physical +3%, Fire +15%",
  "18",
  "2",
  "4",
  "123.00",
  "Ninguém.",
 ],
 [
  "Soulshroud",
  "400",
  "Druids",
  "",
  "Magic Level +4",
  "Death +10%",
  "17",
  "2",
  "4",
  "24.00",
  "Ninguém.",
 ],
 [
  "Spiritthorn Armor",
  "400",
  "Knights",
  "",
  "Sword Fighting +4, Club Fighting +4, Axe Fighting +4",
  "Physical +13%",
  "20",
  "2",
  "4",
  "160.00",
  "Magma Bubble.",
 ],
]
