# Banco de itens (MK_PUBLICAR) - usado no autocomplete de "Publicar anúncio".
# Campos: nome, nivel, vocacao, elemento, bonus, resistencia, atk, def, slots, peso, drop.

_MK_ITENS_DB = [
 [
  "Hailstorm Rod",
  "33",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "27.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Moonlight Rod",
  "33",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "21.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Necrotic Rod",
  "33",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "21.00",
  "Ninguém."
 ],
 [
  "Snakebite Rod",
  "6",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "13",
  "0",
  "1",
  "19.00",
  "Baleful Bunny, Black Sphinx Acolyte, Cobra Vizier, Faceless Bane, Golgordan, Latrivan, Lizard Snakecharmer, Minotaur Cult Zealot, Serpent Spawn, Worm Priestess, Young Goanna."
 ],
 [
  "Springsprout Rod",
  "37",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "27.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Terra Rod",
  "26",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "45",
  "0",
  "1",
  "25.00",
  "Acolyte of the Cult, Adult Goanna, Blemished Spawn, Bloated Man-Maggot, Bonelord, Cobra Vizier, Devourer (Criatura), Drume, Elder Forest Fury, Faceless Bane, Flimsy Lost Soul, Fury, Infernal Phantom, Irgix the Flimsy, Jungle Moister, Lizard Snakecharmer, Madareth, Marid, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Underworld Rod",
  "52",
  "Druids",
  "Death",
  "Nenhum",
  "",
  "75",
  "0",
  "1",
  "29.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Northwind Rod",
  "63",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "85",
  "0",
  "1",
  "29.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Shimmer Rod",
  "65",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "85",
  "0",
  "2",
  "31.00",
  "Adept of the Cult, Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon."
 ],
 [
  "Glacial Rod",
  "65",
  "Druids",
  "Ice",
  "Magic Level +1",
  "",
  "85",
  "0",
  "2",
  "37.00",
  "Droga: Animated Feather, Blemished Spawn, Blightwalker, Bluebeak, Burster Spectre, Crazed Winter Rearguard, Crystal Wolf, Dark Carnisylvan, Faceless Bane, Flimsy Lost Soul, Ice Witch, Infernal Phantom, Irgix the Flimsy, Madareth, Marid, Melting Frozen Horror, Priestess, The Sandking, Tremendous Tyrant, Varnished Diremaw, Werehyaena Shaman. Durante Eventos: Animated Snowman, Ice Dragon, Ice Dragon, Ice Dragon."
 ],
 [
  "Muck Rod",
  "65",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "85",
  "0",
  "2",
  "37.00",
  "Droga: Carnisylvan, ... Durante Invasões: Oodok Witchmaster."
 ],
 [
  "The Chiller",
  "0",
  "Druids",
  "Ice",
  "Nenhum",
  "",
  "6",
  "0",
  "0",
  "15.00",
  "Ninguém."
 ],
 [
  "Ogre Scepta",
  "37",
  "Druids",
  "Earth",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "29.00",
  "Ogre Sage, Ogre Shaman, Shaper Matriarch."
 ],
 [
  "Rod of Destruction",
  "33",
  "Druids",
  "Death",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "27.00",
  "Ninguém."
 ],
 [
  "Sorcerer and Druid Staff",
  "0",
  "",
  "Energy",
  "Nenhum",
  "",
  "25",
  "0",
  "0",
  "19.00",
  "Ninguém."
 ],
 [
  "The Scorcher",
  "0",
  "Sorcerers",
  "Fire",
  "Nenhum",
  "",
  "4",
  "0",
  "0",
  "15.00",
  "Ninguém."
 ],
 [
  "Wand of Vortex",
  "6",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "13",
  "0",
  "1",
  "19.00",
  "Novice of the Cult."
 ],
 [
  "Wand of Dragonbreath",
  "13",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "19",
  "2",
  "1",
  "23.00",
  "Cinder Wyrmling, Crazed Summer Vanguard, Dark Apprentice, Fire Devil, Inkwing, Insane Siren, Manticore, Menacing Carnivor, Herald of Fire."
 ],
 [
  "Wand of Decay",
  "19",
  "Sorcerer",
  "Death",
  "Nenhum",
  "",
  "30",
  "0",
  "1",
  "23.00",
  "Candy Horror, Dark Apprentice, Knowledge Elemental, Menacing Carnivor, Merlkin, Ogre Shaman, Orc Cult Priest, Orc Shaman, Priestess Of The Wild Sun, Shaper Matriarch, Venerable Girtablilu."
 ],
 [
  "Wand of Draconia",
  "22",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "30",
  "2",
  "1",
  "27.00",
  "Blistering Fire Elemental, Crazed Summer Vanguard, Elder Wyrm, Feral Sphinx, Gazer Spectre, Insane Siren, Magma Crawler, Manticore, Ogre Rowdy, Seacrest Serpent, Wyrm."
 ],
 [
  "Wand of Cosmic Energy",
  "26",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "45",
  "0",
  "1",
  "25.00",
  "Amenef The Burning, Arachnophobica, Blemished Spawn, Burster Spectre, Clavius, Diamond Servant, Diamond Servant Replica, Elf Arcanist, Energy Elemental, Flimsy Lost Soul, Gorzindel, High Voltage Elemental, Irgix the Flimsy, Knowledge Elemental, Mercurial Menace, Minotaur Mage, Quara Hydromancer, Quara Hydromancer Scout, Raubritter Chastener, Realityquake, Renegade Quara Hydromancer, Souleater, Sparkion, Spectre, Thanatursus, Tremendous Tyrant, Twisted Shaper, Usurper Warlock, Venerable Girtablilu, Yielothax."
 ],
 [
  "Wand of Inferno",
  "33",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "65",
  "0",
  "1",
  "27.00",
  "Amenef The Burning, Arbaziloth, Dawnfire Asura, Dragon, Draken Spellweaver, Efreet, Eldritch Dragon Lord, Enlightened of the Cult, Essence Of Malice, Feral Sphinx, Gazer Spectre, Gravedigger, Guardian Of Tales, Hand of Cursed Fate, Hellfire Fighter, Hellhound, Insane Siren, Lava Golem, Lizard Dragon Priest, Lokathmor, Madareth, Massive Fire Elemental, Ogre Rowdy, Shaburak Demon, Shaburak Lord, Shaburak Prince, The Baron from Below, The Count Of The Core, The Duke Of The Depths, Thornfire Wolf, True Dawnfire Asura, Vulcongra, Wrathful Archivist, Wyvern."
 ],
 [
  "Wand of Dimensions",
  "37",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "55",
  "0",
  "4",
  "28.00",
  "Mazzinor."
 ],
 [
  "Wand of Starstorm",
  "37",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "65",
  "2",
  "1",
  "25.50",
  "Amenef The Burning, Blemished Spawn, Clavius, Converter, Dark Carnisylvan, Elder Wyrm, Energuardian Of Tales, Flimsy Lost Soul, Headpecker, Infernal Phantom, Irgix the Flimsy, Lloyd, Madareth, Massive Energy Elemental, Mazzinor, Menacing Carnivor, Overcharged Energy Elemental, Poisonous Carnisylvan, Raubritter Chastener, Retching Horror, Shulgrax, Sphinx, Tremendous Tyrant, Usurper Warlock, Varnished Diremaw, Werehyaena Shaman, Wyrm."
 ],
 [
  "Shimmer Wand",
  "40",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "65",
  "0",
  "0",
  "31.00",
  "Ninguém."
 ],
 [
  "Wand of Darkness",
  "41",
  "Sorcerers",
  "Death",
  "Magic Level +2",
  "",
  "85",
  "0",
  "0",
  "32.00",
  "Ninguém."
 ],
 [
  "Wand of Voodoo",
  "42",
  "Sorcerer",
  "Death",
  "Nenhum",
  "",
  "65",
  "2",
  "1",
  "28.50",
  "Black Sphinx Acolyte, Burster Spectre, Carnivostrich, Draken Abomination, Drume, Flimsy Lost Soul, Ghulosh, Grimeleech, Infernal Phantom, Madareth, Menacing Carnivor, Shaper Matriarch, Sharpclaw, Usurper Commander, Undertaker, Venerable Girtablilu, Werebadger, Werehyaena Shaman. Durante Invasões: Feroxa (Mortal)."
 ],
 [
  "Ferumbras' Staff (Wand)",
  "65",
  "Sorcerers",
  "Energy",
  "Nenhum",
  "",
  "95",
  "0",
  "0",
  "22.50",
  "Ninguém."
 ],
 [
  "Wand of Defiance",
  "65",
  "Sorcerer",
  "Energy",
  "Nenhum",
  "",
  "85",
  "0",
  "2",
  "37.00",
  "Bulltaur Forgepriest, Cliff Strider, Essence Of Malice, Harpy, Lady Tenebris, Mercurial Menace, Norcferatu Nightweaver, Orewalker, Seacrest Serpent, Sphinx, Thanatursus, The Souldespoiler, Venerable Girtablilu. Durante Invasões: Mawhawk."
 ],
 [
  "Wand of Everblazing",
  "65",
  "Sorcerer",
  "Fire",
  "Nenhum",
  "",
  "85",
  "0",
  "2",
  "37.00",
  "Adventurer Group, Essence Of Malice, Lava Golem, Magma Crawler, Manticore, Mazoran, Ogre Rowdy, Priestess Of The Wild Sun, Rage Squid, The Source Of Corruption, Weeper, Gaffir. Durante Invasões: Furyosa."
 ],
 [
  "Dream Blossom Staff",
  "80",
  "Sorcerers and Druids",
  "Energy",
  "Nenhum",
  "",
  "70",
  "2",
  "2",
  "32.00",
  "Boogy, Dark Faun, Mercurial Menace, Nymph, Pixie, Pooka, Sugar Mommy."
 ],
 [
  "Ferumbras' Staff (Enchanted Wand)",
  "100",
  "Sorcerers",
  "Energy",
  "Nenhum",
  "",
  "110",
  "0",
  "0",
  "34.00",
  "Ninguém."
 ],
 [
  "Jungle Wand",
  "150",
  "Sorcerers",
  "Earth",
  "Magic Level +1",
  "Ice +3%",
  "80-100",
  "2",
  "4",
  "32.00",
  "Ratmiral Blackwhiskers"
 ],
 [
  "Deepling Ceremonial Dagger",
  "180",
  "Sorcerers and Druids",
  "Ice",
  "Magic Level +1",
  "Earth +5%",
  "90",
  "2",
  "3",
  "32.00",
  "Brokul"
 ],
 [
  "Energized Limb",
  "180",
  "Sorcerers and Druids",
  "Fire",
  "Magic Level +1",
  "Energy +10%",
  "98",
  "2",
  "3",
  "27.00",
  "Maxxenius."
 ],
 [
  "Wand of Destruction",
  "200",
  "Sorcerers",
  "Energy",
  "Nenhum",
  "",
  "88",
  "2",
  "2",
  "35.00",
  "Ninguém."
 ],
 [
  "Lion Wand",
  "220",
  "Sorcerers",
  "Ice",
  "Magic Level +2",
  "",
  "89-109",
  "2",
  "4",
  "21.00",
  "Ancient Lion Knight, Drume."
 ],
 [
  "Deepling Fork",
  "230",
  "Sorcerers and Druids",
  "Ice",
  "Magic Level +2",
  "Holy +8%",
  "90",
  "2",
  "3",
  "33.00",
  "Brokul."
 ],
 [
  "Eldritch Wand",
  "250",
  "Sorcerers",
  "Fire",
  "Magic Level +2, Fire Magic Level +1",
  "Energy +4%",
  "85-105",
  "2",
  "4",
  "36.00",
  "The Brainstealer."
 ],
 [
  "Gilded Eldritch Wand",
  "250",
  "Sorcerers",
  "Fire",
  "Magic Level +2, Fire Magic Level +1",
  "Energy +4%",
  "85-105",
  "2",
  "4",
  "37.00",
  "The Brainstealer."
 ],
 [
  "Naga Wand",
  "250",
  "Sorcerers",
  "Energy",
  "Magic Level +2, Energy Magic Level +1",
  "Ice +4%",
  "90-120",
  "2",
  "4",
  "28.00",
  "Timira the Many-Headed"
 ],
 [
  "Cobra Wand",
  "270",
  "Sorcerers",
  "Energy",
  "Magic Level +2",
  "",
  "95",
  "2",
  "4",
  "19.00",
  "Scarlett Etzel, Gaffir."
 ],
 [
  "Draining Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "1",
  "4",
  "24.00",
  "Ninguém."
 ],
 [
  "Falcon Wand",
  "300",
  "Sorcerer",
  "Energy",
  "Magic Level +3",
  "Fire +8%",
  "100",
  "2",
  "4",
  "33.00",
  "Grand Canon Dominus, Grand Master Oberon."
 ],
 [
  "Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "2",
  "4",
  "24.00",
  "Arbaziloth."
 ],
 [
  "Rending Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "1",
  "4",
  "24.00",
  "Ninguém."
 ],
 [
  "Siphoning Inferniarch Wand",
  "300",
  "Sorcerers",
  "Death",
  "Magic Level +3, Fire Magic Level +1",
  "Earth +5%",
  "95-115",
  "1",
  "4",
  "24.00",
  "Ninguém."
 ],
 [
  "Amber Wand",
  "330",
  "Sorcerers",
  "Energy",
  "Magic Level +2, Energy Magic Level +2",
  "Ice +6%",
  "",
  "2",
  "4",
  "20.00",
  "The Rootkraken."
 ],
 [
  "Soultainter",
  "400",
  "Sorcerers",
  "Death",
  "Magic Level +4",
  "Death +12%",
  "100-120",
  "2",
  "4",
  "19.00",
  "Ninguém."
 ],
 [
  "Crypt Bile",
  "450",
  "Sorcerers",
  "Physical",
  "Magic Level +4",
  "Fire +6%",
  "",
  "2",
  "4",
  "20.00",
  "Ninguém."
 ],
 [
  "Grand Sanguine Coil",
  "600",
  "Sorcerers",
  "Fire",
  "Magic Level +4, Fire Magic Level +1, Energy Magic Level +1",
  "Earth +7%",
  "114",
  "2",
  "4",
  "21.00",
  "Bakragore dentro de uma Bag You Covet."
 ],
 [
  "Sanguine Coil",
  "600",
  "Sorcerers",
  "Fire",
  "Magic Level +4, Fire Magic Level +1, Energy Magic Level +1",
  "Earth +7%",
  "114",
  "2",
  "4",
  "22.00",
  "Bakragore, Chagorz, Ichgahal, Murcion e Vemiath, dentro de uma Bag You Covet."
 ],
 [
  "Moonsilver Channeler",
  "1000",
  "Sorcerers",
  "",
  "Magic Level +6, Death Magic Level +1",
  "Energy +7%",
  "",
  "2",
  "4",
  "23.50",
  "Phosphorus."
 ],
 [
  "Stellar Moonsilver Channeler",
  "1000",
  "Sorcerers",
  "",
  "Magic Level +6, Death Magic Level +1",
  "Energy +7%",
  "",
  "2",
  "4",
  "24.80",
  "Ninguém."
 ]
]
